config/routes.rb
Rails.application.routes.draw do
  devise_for :users ,controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
  }
  root to: 'movies#index'
  get "index_all", to: "movies#index_all"
  get "search", to: 'movies#search'
  get "movie/title", to: "movies#show"
  resource :movies , only: [:index, :show]
  resources :users, only: [:show]
  resources :posts, only: [:create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :movies_uri, only: [:index]

  require 'addressable/uri'


  def index
    trend_select([:trend])
    @num = params[:num]
  end

  def index_all
    @page = params[:content]
    if @page == "index"
      @trend_list = params[:trend_list]
      @name = "title"
      @title = "人気映画一覧"
      @count = @trend_list.size
    elsif @page == "header" or @page == "footer"
      movies_uri
    end
  end


  def search
    code = params[:content_code]
    if code.present?
      search_uri = "https://api.themoviedb.org/3/search/multi?api_key=#{ENV['TMDB_API_KEY']}&language=ja-JA&query=#{code}&include_adult=false"
      enc_uri = Addressable::URI.encode(search_uri)
      uri = URI.parse(enc_uri)
      json = Net::HTTP.get(uri)
      @movies = JSON.parse(json)
      # @base_content = @movies["results"].sort_by { |hash| -hash['popularity'].to_i }
      @base_content = @movies["results"].sort_by { |hash| -hash['popularity'].to_i }
      @cnt = @base_content.size
    else
      redirect_to root_path
    end
  end

  def show
    @content = params[:content]
    @num = params[:num].to_i
    @users = User.pluck(:id, :username)
    @poster_path = Post.pluck(:poster_path)
    @posts = Post.pluck(:user_id, :review, :image, :body, :submitter, :id, :created_at, :poster_path)
    session[:content] = @content
  end

  private

    def movies_uri
      search_uri = "https://api.themoviedb.org/3/trending/movie/week?api_key=#{ENV['TMDB_API_KEY']}&language=ja-JA"
      enc_uri = Addressable::URI.encode(search_uri)
      uri = URI.parse(enc_uri)

      response = Net::HTTP.start(uri.host, uri.port) do |http|
        # 接続時の待機時間
        http.open_timeout = 10
        # ブロックする最大秒数
        http.read_timeout = 20
        # APIをリクエスト
        json = Net::HTTP.get(uri)
        @movies = JSON.parse(json)
      end
      # 例外処理
      begin
        # @movies = JSON.parse(json)
        @movies_content = @movies["results"].sort_by { |hash| -hash['popularity'].to_i }
        @count = @movies_content.size
        # エラー処理
      rescue => e
        @message = e.message
      end

      # json = Net::HTTP.get(uri)
      # @movies = JSON.parse(json)
      # @movies_content = @movies["results"].sort_by { |hash| -hash['popularity'].to_i }
      # @count = @movies_content.size
    end

    def trend_select(code)
      search_uri = "https://api.themoviedb.org/3/search/movie?api_key=#{ENV['TMDB_API_KEY']}&language=ja-JA&query=#{code}&include_adult=false"
      enc_uri = Addressable::URI.encode(search_uri)
      uri = URI.parse(enc_uri)
      json = Net::HTTP.get(uri)
      @movies = JSON.parse(json)
      @base_content = @movies["results"]
      @cnt = @base_content.size
    end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def content_select(code)
    search_uri = "https://api.themoviedb.org/3/search/movie?api_key=#{ENV['TMDB_API_KEY']}&language=ja-JA&query=#{code}&include_adult=false"
    enc_uri = Addressable::URI.encode(search_uri)
    uri = URI.parse(enc_uri)
    json = Net::HTTP.get(uri)
    @movies = JSON.parse(json)
    @base_content = @movies["results"]
    @cnt = @base_content.size
  end

  def trend_name(count, type)
     i = 0
     @trend_list = []
     while i < count
       @trend_list.push(type[i]["title"])
       i += 1
     end
  end

  def bubble_sort(ary)
    length = ary.length
    (1..length).each do |i|
      (1..(length - i)).each do |jx|
        jy = jx - 1
        if ary[jy][6].to_s < ary[jx][6].to_s
          tmp = ary[jy]
          ary[jy] = ary[jx]
          ary[jx] = tmp
        end
      end
    end
    ary
  end
end

app/views/movies/_index.html.erb
<% case content %>
  <% when "movie" %>
    <% type =  @movies_content %>
    <% name = "title" %>
    <% title = "映画" %>
    <% count = @count %>
<% end %>


<% i = 0  %>
<% mtrend_name = [] %>
<% while i < @count %>
  <% mtrend_name.push(type[i][name]) %>
  <% i += 1 %>
<% end %>

<% t = 0 %>
<% content_arr = [] %>
<div class="main-index">
  <h2>人気の<%= title %></h2>
  <div class="content-box">
    <% t = 0 %>
    <% while t < 5 %>
      <% trend = mtrend_name[t]  %>
      <% content_select(trend) %>
      <div class="card card-main" style="width: 18rem;">
        <%= image_tag "https://image.tmdb.org/t/p/w300/#{@base_content[0]["poster_path"]}", class:"card-img-top" %>
          <div class="card-body">
            <h4><%= @base_content[0][name] %></h4>
            <p class="card-text"><%= @base_content[0]["overview"].truncate(20) %>.</p>
          </div>
          <% content_arr.push(@base_content[0]) %>
          <%= link_to "詳細ページを開く", movies_path(content: @base_content[0], num: 1 ), class:"btn btn-primary" %>
      </div>
      <% t += 1 %>
    <% end %>
  </div>
  <%= link_to "おすすめの#{title}一覧", index_all_path(trend_list: mtrend_name, content: "index" ), class: "top-link" %>
</div>

app/views/movies/_index_all.html.erb
<% if @page == "header" or @page == "footer"   %>
  <% trend_name(@count, @movies_content) %>
<% end %>

<h1><%= @title %></h1>
<% content_arr = [] %>
<div class="main">
  <% i = 0 %>
  <% if  !@count.zero? %>
    <% while i < @count %>
      <div class="card index-card" style="width: 18rem;">
        <% trend = @trend_list[i]  %>
        <% content_select(trend) %>
        <% type = @base_content %>
        <%= image_tag "https://image.tmdb.org/t/p/w300/#{type[0]["poster_path"]}", class:"card-img-top" %>
          <div class="card-body">
            <h4><%= type[0]["title"] %></h4>
            <p class="card-text"><%= type[0]["overview"].truncate(20) %></p>
          </div>
          <% content_arr.push(type[i]) %>
          <%= link_to "詳細ページを開く", movies_path(content: type[0], num: 1 ), class:"btn btn-primary" %>
      </div>
      <% i += 1 %>
    <% end %>
  <% else %>
    <p>検索結果は何もありませんでした。</p>
    <p>別の検索ワードで試して見てください。</p>
  <% end %>
</div>

app/views/movies/_search.html.erb
<% case content %>
  <% when "search" %>
    <% type =  @base_content %>
    <% name = "title" %>
    <% title = "検索結果一覧" %>
<% end %>


<h1><%= title %></h1>


<% content_arr = [] %>
<div class="main">
  <% i = 0 %>
  <% if  @cnt > 0 %>
    <% while i < @cnt %>
      <div class="card index-card" style="width: 18rem;">
        <%= image_tag "https://image.tmdb.org/t/p/w300/#{type[i]["poster_path"]}", class:"card-img-top" %>
          <div class="card-body">
            <p><%= type[i][name] %></p>
            <p class="card-text"><%= type[i]["overview"].truncate(20) %></p>
          </div>
          <% content_arr.push(type[i]) %>
          <%= link_to "詳細ページを開く", movies_path(content: type[i], num: 1 ), class:"btn btn-primary" %>
      </div>
      <% i += 1 %>
    <% end %>
  <% else %>
    <p>検索結果は何もありませんでした。</p>
    <p>別の検索ワードで試して見てください。</p>
  <% end %>
</div>

app/views/movies/index.html.erb
<%= render partial: 'index',locals:{ content: "movie"} %>

app/views/movies/index_all.html.erb
<%= render partial: 'index_all' %>

app/views/movies/search.html.erb
<%= render partial: 'search',locals:{ content: "search"} %>

app/views/movies/show.html.erb
<% type = @content ? type = @content : type = cont  %>
<% image = "https://image.tmdb.org/t/p/w300/#{type["poster_path"]}" %>
<% title = type["title"]  %>
<% release_date = type["release_date"] %>
<% overview = type["overview"] %>
<% vote_average = type["vote_average"] %>
<% vote_count = type["vote_count"] %>
<% poster_path = type["poster_path"] %>
<% content = {"image": image,"title":title,"release_date": release_date,
                "overview": overview,"vote_average":vote_average,
                "vote_count":vote_count, "poster_path": poster_path } %>



<div class="card mb-3 show-box">
  <%= image_tag image, class:"show-img rounded mx-auto d-block" %>
  <table class="table">
    <tbody>
      <tr class="tr-title">
        <th scope="row" class="th">タイトル</th>
        <td><h4><%= title %></h4></td>
      </tr>
      <tr class="tr-title">
        <th scope="row" class="th">公開日</th>
        <td><%= release_date %></td>
      </tr>
      <tr class="tr-title">
        <th scope="row" class="th">説明</th>
        <td><%= overview %></td>
      </tr>
      <tr class="tr-title">
        <th scope="row" class="th">評価</th>
        <td><%= vote_average %></td>
      </tr>
    </tbody>
  </table>
  <%= link_to "戻る", :back %>
</div>



<% if user_signed_in? %>
  <div class="input-area">
    <%= form_with model: Post.new do |f| %>
      <%= f.text_area :body, placeholder: "コメントを入力してください",  size: "60x5" %><br />
      <%= f.hidden_field :id, {value: current_user.id} %>
      <%= f.select :review, {"1":1, "2":2, "3":3, "4":4, "5":5,"6":6,"7":7, "8":8, "9":9,"10":10} %>
      <%= f.hidden_field :image, {value: image}  %>
      <%= f.hidden_field :poster_path, {value: poster_path}  %>
      <%= f.submit "送信" %>
    <% end %>
  </div>


  <div class="coment-area">
  <% if @posts != nil %>
    <% user =  @users.to_h %>
    <% bubble_sort(@posts) %>
    <% len = @posts.length; @posts.each_with_index { |post, i| %>
      <% if post[7] ==  poster_path %>
        <table>
          <tr>
            <th scope="row" class="th">No:</th>
            <td><h4><%= (len-i).to_s %></h4></td>
          </tr>
          <tr>
            <th scope="row" class="th">評価</th>
            <td><h4><%= post[1] %></h4></td>
          </tr>
          <tr>
            <th scope="row" class="th">コメント</th>
            <td><h4><%= post[3] %></h4>
              <% if post[0] == current_user.id %>
                <%= link_to  edit_post_path(post[5]) do  %>
                  <i class="fas fa-pen"></i>
                <% end %>
                <%= link_to  post_path(post[5]), method: :delete, data: {confirm: "本当に削除しますか？"} do %>
                  <i class="fa fa-trash" aria-hidden="true"></i>
                <% end %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th scope="row" class="th">ユーザー</th>
            <td><h4><%= link_to user[post[0]], "/users/#{post[0]}" %></h4></td>
          </tr>
        </table>
        <p><%= post[6].strftime("%Y/%D:%H:%M") %></p>
      <% end %>
    <% } %>
  <% end %>
  </div>
<% end %>