config/routes.rb
Rails.application.routes.draw do
  devise_for :users ,controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
  }
  root to: 'movies#index'
  get "index_all", to: "movies#index_all"
  get "search", to: 'movies#search'
  get "movie/title", to: "movies#show"
  resource :movies , only: [:index, :show]
  resources :users, only: [:show]
  resources :posts, only: [:create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :posts, dependent: :destroy
  has_one_attached :avatar
  devise :database_authenticatable, :registerable,
         :rememberable, :validatable

  validates :username, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true

  mount_uploader :image, ImageUploader

  def email_required?
    false
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  def update
    super
    if account_update_params[:avatar].present?
      resource.avatar.attach(account_update_params[:avatar, :email, :profile, :username, :image])
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar, :email, :profile, :username, :image])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar, :email, :profile, :username, :image])
  end

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:username])
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :edit]
  before_action :user_params, only: [:edit]

  def show
    @users = User.where(role: "user") if @user.role == "admin"
    @posts = Post.where(user_id: @user.id).order("created_at desc").where.not(image: nil)
  end

  def edit
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :introduce, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end
end

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="user-page">
  <div class="user-info">
    <% if @user.image? %>
      <%= image_tag @user.image.url(:thumb), class: "rounded-circle" %>
    <% else %>
      <%= gravatar_for @user %>
    <% end %>
    <br />
    <strong>ユーザーネーム:</strong>
    <%= @user.username %>
  </div>

  <div class="user-prof">
    <strong>プロフィール:</strong><br />
    <% if @user.profile? %>
      <%= @user.profile %>
    <% else %>
      <p>よろしくお願いします！！！</p>
    <% end %>
  </div>

  <div class="user-info">
    <%= link_to edit_user_registration_path do %>
      <i class="fas fa-pen">ユーザー情報編集</i>
    <% end %>
    <%= link_to "戻る", :back %>
  </div>
</div>

<% if @users != nil  %>
  <ul>
    <% @users.each { |user| %>
      <li><%= link_to user.username, user_path(user.id) %></li>
    <% } %>
  </ul>
<% end %>


<% if @posts != nil %>
  <% l = @posts.length; @posts.each_with_index { |post, i|
    # image_tag post.image
    submitter = User.find_by(id: post.submitter)
    sname = (submitter != nil) ? submitter.username : "Anonymous"  %>
    <div class="review_area">
      <div class="image_area">
        <%= image_tag post.image ,class:"user_page_image"%><br />
        <table class="reviw-table">
          <tbody>
            <tr class="tr-title">
              <td class="td-title">No:</td>
              <td  class="td-body"><%= (l-i).to_s %></td>
            </tr>
            <tr class="tr-title">
              <td class="td-title">評価:</td>
              <td  class="td-body"><%= post.review %></td>
            </tr>
            <tr class="tr-title">
              <td class="td-title">コメント:</td>
              <td  class="td-body"><%= post.body %>
                <% if post.user_id == current_user.id %>
                  <%= link_to  edit_post_path(post.id) do  %>
                    <i class="fas fa-pen"></i>
                  <% end %>
                  <%= link_to  post_path(post.id), method: :delete, data: {confirm: "本当に削除しますか？"} do %>
                    <i class="fa fa-trash" aria-hidden="true"></i>
                  <% end %>
                <% end %>
              </td>
            </tr>
            <tr class="tr-title">
              <td class="td-title">評価日時:</td>
              <td  class="td-body"><%= post.created_at.strftime("%Y/%D:%H:%M") %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  <% } %>
<% end %>