config/routes.rb
Rails.application.routes.draw do
  devise_for :users ,controllers: {
    sessions: "users/sessions",
    passwords: "users/passwords",
    registrations: "users/registrations",
  }
  root to: 'movies#index'
  get "index_all", to: "movies#index_all"
  get "search", to: 'movies#search'
  get "movie/title", to: "movies#show"
  resource :movies , only: [:index, :show]
  resources :users, only: [:show]
  resources :posts, only: [:create, :edit, :update, :destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/partial/_footer.html.erb
<footer>
  <div class="footer-item">
    <ul class="nav-footer">
      <li class="nav-item">
        <%= link_to "Top", root_path ,class:"link-menu" %>
      </li>
      <li class="nav-item">
        <%= link_to "おすすめ映画一覧",index_all_path(content: "footer"), class: "link-menu"  %>
      </li>
    </ul>

  </div>
</footer>

app/views/partial/_header.html.erb
<header>
  <%= link_to root_path do %>
    <%= image_tag "twitter_header_photo_2.png" , class:"logo"%>
  <% end %>
  <div class="header-item">
    <ul class="nav">
      <li class="nav-item">
        <%= link_to "Top", root_path , class: "link-menu"  %>
      </li>
      <li class="nav-item">
        <%= link_to "おすすめ映画一覧",index_all_path(content: "header"), class: "link-menu"  %>
      </li>
    </ul>
    <div class="user-menus">
      <% if user_signed_in? %>
        <button type="button" name="button" class="btn btn-primary  user-btn">
          <%= link_to "マイページ", "/users/#{current_user.id}" , class: "user-item"  %>
        </button>
        <button type="button" name="button" class="btn btn-primary user-btn">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete ,class: "user-item" %>
        </button>
      <% else %>
        <button type="button" name="button" class="btn btn-primary user-btn">
          <%= link_to "ログイン", new_user_session_path ,class: "user-item" %>
        </button>
        <button type="button" name="button" class="btn btn-primary  user-btn">
          <%= link_to "サインイン", new_user_registration_path, class: "user-item"  %>
        </button>
      <% end %>
    </div>
    <div class="search_area">
      <%= form_with url: search_path, method: :get,class:"search_form" ,local: true do |f| %>
        <% f.text_field :content_code, class: "search_form", placeholder: "映画のタイトルを入力してください" %>
      <% end %>
    </div>
  </div>
</header>